name: shinobiWay
version: '${project.version}'
main: eportela.shinobiway.ShinobiWay
authors: [eportela]
description: plugin 
website: https://github.com/empsa1

commands:
  shinobiGroup:
    description: Your command description here
    usage: /shinobiGroup <subcommand>
    permission: shinobiway.shinobigroup.*